# -*- coding: utf-8 -*-
"""u07_출력.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10lki9ISlcKVPAGDhhGu6CTSomfFww1k_

#Unit 7. 출력
"""

a, b = map(int, input('정수 두개 입력> ').split())
a
b

a, b = map(int, input('정수 두개 입력> ').split())
print(a)
print(b)

print(a, b)

print(a, b, sep=',')

